/// gRPC service implementation for the GraphService.
///
/// Wraps the in-memory graph store behind an Arc<RwLock> for concurrent access
/// and implements the proto-defined service methods.

use std::sync::Arc;
use tokio::sync::RwLock;
use tonic::Status;

use crate::graph::store::InfraGraph;
use crate::server::handlers;

/// The gRPC service implementation holding a thread-safe reference to the graph.
pub struct GraphServiceImpl {
    /// Thread-safe, concurrent-read graph store.
    pub graph: Arc<RwLock<InfraGraph>>,
}

impl GraphServiceImpl {
    /// Create a new GraphServiceImpl with the given graph store.
    pub fn new(graph: Arc<RwLock<InfraGraph>>) -> Self {
        Self { graph }
    }
}

/// Placeholder module representing compiled proto definitions.
/// In a real build, tonic-build generates this from graph.proto.
pub mod proto {
    /// Placeholder for the generated graph service server trait.
    /// In production, this is generated by tonic-build from the .proto file.

    #[derive(Debug, Clone)]
    pub struct QueryNodesRequest {
        pub types: Vec<i32>,
        pub filters: std::collections::HashMap<String, String>,
        pub min_risk_score: f64,
        pub page_size: i32,
        pub page_token: String,
    }

    #[derive(Debug, Clone)]
    pub struct QueryNodesResponse {
        pub nodes: Vec<ProtoNode>,
        pub next_page_token: String,
        pub total_count: i32,
    }

    #[derive(Debug, Clone)]
    pub struct QueryEdgesRequest {
        pub types: Vec<i32>,
        pub source_id: String,
        pub target_id: String,
        pub page_size: i32,
        pub page_token: String,
    }

    #[derive(Debug, Clone)]
    pub struct QueryEdgesResponse {
        pub edges: Vec<ProtoEdge>,
        pub next_page_token: String,
        pub total_count: i32,
    }

    #[derive(Debug, Clone)]
    pub struct FindPathsRequest {
        pub source_id: String,
        pub target_id: String,
        pub max_depth: i32,
        pub max_paths: i32,
        pub allowed_edge_types: Vec<i32>,
    }

    #[derive(Debug, Clone)]
    pub struct FindPathsResponse {
        pub paths: Vec<ProtoPath>,
        pub total_paths_found: i32,
    }

    #[derive(Debug, Clone)]
    pub struct ComputeBlastRadiusRequest {
        pub node_id: String,
        pub max_depth: i32,
        pub edge_types: Vec<i32>,
    }

    #[derive(Debug, Clone)]
    pub struct BlastRadiusResult {
        pub origin_id: String,
        pub affected_nodes: Vec<ProtoNode>,
        pub traversed_edges: Vec<ProtoEdge>,
        pub total_affected: i32,
        pub aggregate_risk_score: f64,
        pub affected_by_type: std::collections::HashMap<String, i32>,
    }

    #[derive(Debug, Clone)]
    pub struct GetCriticalNodesRequest {
        pub top_n: i32,
        pub types: Vec<i32>,
        pub scoring_algorithm: String,
    }

    #[derive(Debug, Clone)]
    pub struct GetCriticalNodesResponse {
        pub critical_nodes: Vec<ProtoCriticalNode>,
    }

    #[derive(Debug, Clone)]
    pub struct ProtoNode {
        pub id: String,
        pub name: String,
        pub node_type: i32,
        pub properties: std::collections::HashMap<String, String>,
        pub risk_score: f64,
    }

    #[derive(Debug, Clone)]
    pub struct ProtoEdge {
        pub id: String,
        pub source_id: String,
        pub target_id: String,
        pub edge_type: i32,
        pub weight: f64,
        pub properties: std::collections::HashMap<String, String>,
    }

    #[derive(Debug, Clone)]
    pub struct ProtoPath {
        pub nodes: Vec<ProtoNode>,
        pub edges: Vec<ProtoEdge>,
        pub total_weight: f64,
        pub hop_count: i32,
    }

    #[derive(Debug, Clone)]
    pub struct ProtoCriticalNode {
        pub node: Option<ProtoNode>,
        pub criticality_score: f64,
        pub incoming_paths: i32,
        pub outgoing_paths: i32,
        pub betweenness_centrality: f64,
    }
}

// ---------------------------------------------------------------------------
// Service Implementation
// ---------------------------------------------------------------------------

impl GraphServiceImpl {
    /// Query nodes matching the given filters.
    pub async fn query_nodes(
        &self,
        request: proto::QueryNodesRequest,
    ) -> Result<proto::QueryNodesResponse, Status> {
        let graph = self.graph.read().await;
        let result = handlers::handle_query_nodes(&graph, &request)?;
        Ok(result)
    }

    /// Query edges matching the given filters.
    pub async fn query_edges(
        &self,
        request: proto::QueryEdgesRequest,
    ) -> Result<proto::QueryEdgesResponse, Status> {
        let graph = self.graph.read().await;
        let result = handlers::handle_query_edges(&graph, &request)?;
        Ok(result)
    }

    /// Find paths between two nodes.
    pub async fn find_paths(
        &self,
        request: proto::FindPathsRequest,
    ) -> Result<proto::FindPathsResponse, Status> {
        let graph = self.graph.read().await;
        let result = handlers::handle_find_paths(&graph, &request)?;
        Ok(result)
    }

    /// Compute blast radius from a compromised node.
    pub async fn compute_blast_radius(
        &self,
        request: proto::ComputeBlastRadiusRequest,
    ) -> Result<proto::BlastRadiusResult, Status> {
        let graph = self.graph.read().await;
        let result = handlers::handle_compute_blast_radius(&graph, &request)?;
        Ok(result)
    }

    /// Get the most critical nodes in the graph.
    pub async fn get_critical_nodes(
        &self,
        request: proto::GetCriticalNodesRequest,
    ) -> Result<proto::GetCriticalNodesResponse, Status> {
        let graph = self.graph.read().await;
        let result = handlers::handle_get_critical_nodes(&graph, &request)?;
        Ok(result)
    }
}
